workdir: $GOPATH/src/cirello.io/snippetsd
observe: *.go
ignore: /vendor
build-backend: go install -tags "libsqlite3 darwin" ./cmd/snippetsd
backend:       $GOPATH/bin/snippetsd http
ui:            restart=tmp cd frontend; npm run start
